using SIMS.Web.Models;
using SIMS.Web.Repositories;

namespace SIMS.Web.Services
{
    public class StudentService
    {
        private readonly IRepository<Student> _repository;

        public StudentService(IRepository<Student> repository)
        {
            _repository = repository;
        }

        public async Task<List<Student>> GetAllStudentsAsync()
            => await _repository.GetAllAsync();

        public async Task<Student?> GetStudentAsync(string id)
            => await _repository.GetByIdAsync(id);

        public async Task RegisterStudentAsync(Student student)
        {
            // StudentId is auto-generated by the database, no need to assign
            student.EnrollmentDate = DateTime.Now;
            await _repository.AddAsync(student);
        }

        public async Task UpdateStudentAsync(Student student)
            => await _repository.UpdateAsync(student);

        public async Task DeleteStudentAsync(string id)
            => await _repository.DeleteAsync(id);
    }
}
